# Generated by Django 4.2.23 on 2025-09-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('emergency_contact', models.IntegerField(max_length=10)),
                ('unique_id', models.UUIDField(editable=False, unique=True)),
            ],
        ),
    ]
