# Generated by Django 4.2.23 on 2025-09-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vahansathi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='emergency_contact',
        ),
        migrations.AddField(
            model_name='userdata',
            name='emergency_contact1',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='emergency_contact2',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
