# Generated by Django 4.2.23 on 2025-09-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vahansathi', '0002_remove_userdata_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
