# Generated by Django 4.2.23 on 2025-09-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
